name: 🚀 云端锻造厂

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 拉取代码
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 🔧 请出真正的太上老君 NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e

    - name: 🐍 配置 Python 引擎
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 🛠️ 启动极简编译脚本
      # 这里自动读取上面下载好的 NDK 路径，天衣无缝！
      run: python build.py --ndk ${{ steps.setup-ndk.outputs.ndk-path }} zip

    - name: 🎁 打包并上传成果
      uses: actions/upload-artifact@v4
      with:
        name: LightyHDR-Zygisk-Module
        path: out/*.zip
